source "https://rubygems.org"

gem "aws-sdk"
gem "alephant-logger", "1.2.0"
gem "alephant-publisher-queue"
gem "dotenv"
gem "bbc-cosmos-config"
gem "htmlentities"
gem "alephant-harness"
gem "dim"
gem "spoon"

group :test do
  gem "rspec"
  gem "rack-test"
  gem "faraday"
  gem "json-schema"
  gem "nokogiri"
  gem "json"
end

group :development do
  gem "spurious-ruby-awssdk-helper"
  gem "spurious"
  gem "alephant-preview", :git => 'https://github.com/BBC-News/alephant-preview', :branch => 'allow-port-modification'
  gem "rake"
  gem "guard"
  gem "guard-rspec"
  gem "rspec-nc"
  gem "pry"
  gem "pry-remote"
  gem "pry-nav"
end
